language: cpp
sudo: true
dist: trusty
compiler:
- g++
os:
- linux

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - lcov
            - cmake3

branches:
  only:
  - master

script: ./build.sh

after_success:
       - cd ${TRAVIS_BUILD_DIR}
       - lcov --directory . --capture --output-file coverage.info
       - lcov --remove coverage.info '/usr/*' --output-file coverage.info
       - lcov --list coverage.info
       - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
    
       notifications:
         email:
         - codymhaas@gmail.com
    
           env:
             global:
             - LANG="en_US.UTF-8"
